### ISSUE TITLE
Configure auto uploading of new releases to PyPi

### ISSUE THREAD

**Issue by lorddaedra** [ory/sdk#100]
https://github.com/ory/sdk/tree/master/clients/keto/python Current version: v0.6.0-alpha.6
https://pypi.org/project/ory-keto-client/ Current version: 0.5.2

You can use Poetry, for example. https://python-poetry.org/docs/cli/#publish

**Comment by aeneasr** [comment]
I see several 0.6 releases in the list: https://pypi.org/project/ory-keto-client/#history
