### ISSUE TITLE
Typescript SDK appears to malform request body

### ISSUE THREAD

**Issue by Karlinator** [ory/sdk#107]
**Describe the bug**

The `hydraAdmin.acceptLoginRequest()` function appears to be escaping the input incorrectly, ending up with a JSON string which is simply not valid. I have tested that the endpoint in Hydra works, but my attempts to call it from this SDK do not.

The raw request body produced by the SDK is `"{\"subject\":\"someuser\"}"`, rather than `{"subject": "someuser"}`

**To Reproduce**

1. Setup a flow and call `acceptLoginRequest()`
2. Watch the 400 error come back.

I'm afraid I don't have a reproduction repo set up.

**Expected behavior**

The function should form the request body correctly.

**Environment**

- Version: v1.10.6
- Running in SvelteKit, but the issue persists in both Node and browser contexts

**Additional context**

I've also, for the introspection abilities, tried calling this from a browser, and findings agree.

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/issues/2718 :)

**Comment by Karlinator** [comment]
Thanks! Axios fixed this upstream :)
