### ISSUE TITLE
Generated Dart code is not compilable / usable

### ISSUE THREAD

**Issue by aeneasr** [ory/sdk#109]
**Describe the bug**

Unfortunately, none of the DartJS SDKs are usable as the generators are still work in progress over at https://github.com/OpenAPITools/openapi-generator

While we publish SDKs, and have a build and test pipeline, the code is unfortunately not usable at this time.

Please stay tuned until the templates in OpenAPI Generator are improved. Thank you!

**Comment by jld3103** [comment]
I've written a kratos client for my company that already implements most of the endpoints. We are working on an admin dashboard that will be open-sourced soon. The client is in separate package, so that it could be used by other people. It also doesn't have the issues from https://github.com/ory/kratos/issues/1739, because I fixed them in the client when I implemented it.

**Comment by aeneasr** [comment]
Oh nice, could you link it here? Also we’re looking for people who could help implement/improve the openapi dart generator so that we can improve the official SDK!

**Comment by jld3103** [comment]
Yes I will link it, once we publish it. I'm also interested in fixing the generator, but I don't know much about it yet.

**Comment by jld3103** [comment]
So I want to try to fix the openapi generator. I'm not sure if I can actually do it though, because I don't know much about the generator itself. I will also directly add null-safety support like suggested in the linked issue.

**Comment by jld3103** [comment]
@aeneasr btw it's Dart and not DartJS ;)

**Comment by jld3103** [comment]
So I already made good progress and the code is compilable, but the it's not compatible to the kratos api for example. The problem is that it just doesn't care about some cases that are used by the kratos api. It will take a bit more effort, but I'll get it done for sure.

**Comment by aeneasr** [comment]
Awesome! :))

**Comment by hpadrao** [comment]
Any news?

**Comment by jld3103** [comment]
See https://github.com/ory/cloud/issues/13#issuecomment-1027275858

**Comment by aeneasr** [comment]
Closing in favor of #13
