### ISSUE TITLE
Clean up artifacts before publishing

### ISSUE THREAD

**Issue by loposkin** [ory/sdk#112]
**Describe the bug**

Generated SDKs for version v0.7.6 use an old path for submitting verification flow, namely `/self-service/verification/methods/link`. That causes CORS errors(using flows for native apps) for us.  For example, this is the case for [Java SDK](https://github.com/ory/kratos-client-java/blob/d2ee31edf34b2870eeb0535604991516fa9caa7d/src/main/java/sh/ory/kratos/api/PublicApi.java#L2952). 

**Expected behavior**

According to documentation for v0.7.6, the path for submitting verification flow is now `self-service/verification`

**Environment**

- Version: v0.7.6
- Java SDK (probably other SDKs as well)

**Comment by aeneasr** [comment]
Thank you for the report! Which SDK method are you using?

**Comment by aeneasr** [comment]
Ah sorry, you linked it! It’s strange though - the method appears to be correctly documented:

https://github.com/ory/kratos/blob/eca7aff2be96c673dd6be5dc36ab1f4850cc44f0/selfservice/flow/verification/handler.go#L286

Looking at the SDK though, you are using PublicAPI which is an old artifact that should no longer exist. If you use the v0aplha1 API it should work?

Not sure why rhis isn’t being cleaned up properly. Might be an issue im the code generation!

**Comment by loposkin** [comment]
Hi, thank you for your answer! I was not aware that `PublicApi` is an artifact. We'll replace it with `V0alpha1Api`. Thanks!

**Comment by aeneasr** [comment]
Resolved
