### ISSUE TITLE
Exported enums removed in patch `regenerate OpenAPI client v0.7.5-alpha.2`

### ISSUE THREAD

**Issue by fmmoret** [ory/sdk#118]
**Describe the bug**

A large number of exported enums disappeared from
https://github.com/ory/sdk/blame/master/clients/kratos/typescript/api.ts

We were using:
  SubmitSelfServiceLoginFlowWithPasswordMethodBodyMethodEnum,
  SubmitSelfServiceRecoveryFlowWithLinkMethodBodyMethodEnum,
  SubmitSelfServiceRegistrationFlowWithPasswordMethodBodyMethodEnum,
  SubmitSelfServiceSettingsFlowWithPasswordMethodBodyMethodEnum,

To give some examples that were deleted:
```
/**
    * @export
    * @enum {string}
    */
export enum SubmitSelfServiceLoginFlowWithPasswordMethodBodyMethodEnum {
    Password = 'password',
    Oidc = 'oidc'
}

/**
    * @export
    * @enum {string}
    */
export enum SubmitSelfServiceRecoveryFlowWithLinkMethodBodyMethodEnum {
    Link = 'link'
}


/**
    * @export
    * @enum {string}
    */
export enum SubmitSelfServiceRegistrationFlowWithPasswordMethodBodyMethodEnum {
    Password = 'password',
    Oidc = 'oidc'
}
```

All locations that used these as types:
```
method: SubmitSelfServiceRegistrationFlowWithPasswordMethodBodyMethodEnum
```

for example became
```
method: string
```

**To Reproduce**

Edits contained in this pr:
https://github.com/ory/sdk/commit/680b1fc960a64b1e1ca4cb90ae93c83b170a20e1

**Expected behavior**

Enums should still exist and be exported? The http api explorer has these enums in dropdowns. https://www.ory.sh/kratos/docs/reference/api#operation/submitSelfServiceLoginFlow

**Comment by aeneasr** [comment]
These were unfortunately deleted on purpose as openapi discriminators did not work well with enums (or rather at all) in multiple generators :/

**Comment by fmmoret** [comment]
Hmm. Typescript union types would be less prone to disaster, but I don't see support in this lib -- ideal case would be something like this https://github.com/ferdikoomen/openapi-typescript-codegen#enums-vs-union-types---useuniontypes

**Comment by aeneasr** [comment]
Yeah, it's not about TypeScript but about other languages like Dart or C# :) Those generators can not handle this well. Also, I believe that ENUMS are not really supposed to be used in combination with discriminators :/

**Comment by fmmoret** [comment]
🥀
