### ISSUE TITLE
Why .net C# sdk requests are running for a long time?

### ISSUE THREAD

**Issue by khheckfy** [ory/sdk#121]
Hi!
If I call directly through the postman Kratos, then everything works out within 0.3 seconds
Also, if in the C # code I call a request through RestSharp or through HttpClient, then the results are the same.

But through RestSharp it is about 2 times slower through HttpClient

But if I use your SDK, then the flow request for registration takes 1 second, and the submit takes 5 seconds

What can be wrong?
Example in screenshots:
![image](https://user-images.githubusercontent.com/23306636/138592720-b75de9ac-e483-45fe-adad-62048265bde5.png)
![image](https://user-images.githubusercontent.com/23306636/138592724-d84e3b16-5f7a-4070-8dbf-d1ea62b75d7c.png)

In the code above, there is a call to the SDK
Below is an example of a call without SDK but using httpClient and RestSharp

![image](https://user-images.githubusercontent.com/23306636/138592763-5fcebdce-ff16-42ee-9925-0a57d168ab14.png)

And the last example below is a call to the kratos service via postman

![image](https://user-images.githubusercontent.com/23306636/138592793-c081daa9-081a-4e58-abaa-46287889c07f.png)

**Comment by aeneasr** [comment]
Closing as I think this is answered
