### ISSUE TITLE
Generate SDK for elm

### ISSUE THREAD

**Issue by afreakk** [ory/sdk#126]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to use Ory sdk's for elm.

### Describe your ideal solution

It would be nice to be able to use generated sdk for elm

### Workarounds or alternatives

Openapi-generator-cli has some support for elm.
But when generating using
`openapi-generator-cli generate -i v0.8.0-alpha.2.json -g elm`
it does generate mostly working code, but it for instance generates a broken type
```
type alias UiNodeInputAttributeType =
    { }
```
which i suspect is the reason this function also gets broken:
```
encodeUiNodeInputAttributeTypePairs : UiNodeInputAttributeType -> List EncodedField
encodeUiNodeInputAttributeTypePairs model =
    let
        pairs =
            ]
    in
    pairs
```
(Also has more issues, like AnyType and Object)

### Version

v0.8.0-alpha-2 (also using hydra and oathkeeper)

**Comment by aeneasr** [comment]
Thank you for the report! Looks like some things need to be fixed in openapi-generator first though :/
