### ISSUE TITLE
[Rust SDK] Kratos 0.8.x is not publishing to crates.io

### ISSUE THREAD

**Issue by hzuo** [ory/sdk#127]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The latest published version is still from 2 months ago, 0.7.6-alpha.7:
https://crates.io/crates/ory-kratos-client/versions

### Reproducing the bug

Go to https://crates.io/crates/ory-kratos-client/versions

### Version

n/a

**Comment by aeneasr** [comment]
Thank you! This was caused by a broken openapi generator version. Should be fixed with the next release hopefully!

**Comment by hzuo** [comment]
Hey @aeneasr - curious when the next release will be? We're eager to pull in the great stuff in 0.8.x!

**Comment by hzuo** [comment]
Fixed since 0.8.2-alpha.1: https://crates.io/crates/ory-kratos-client/0.8.2-alpha.1

Thank you!
