### ISSUE TITLE
[Golang SDK] Hydra 1.10.6 PatchOAuth2Client always updates the client secret

### ISSUE THREAD

**Issue by xiaofei-du** [ory/sdk#129]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi, I am using the Golang SDK `hydra-client-go v1.10.6`, when I update a client's name, the client secret is also updated. 

**Expected result:**
Only the client name is updated.

**Actual result:**
Both the client name and client secret are updated.

### Reproducing the bug

My code:

```golang
op := "replace"
path := "/client_name"

r, e := client.Admin.PatchOAuth2Client(admin.NewPatchOAuth2ClientParams().WithID(id).WithBody(
    models.PatchRequest{{
    Op: &op,
    Path: &path,
    Value: "updated_client_name",
  }}))
```
The returned `r.Payload.ClientSecret` is not empty, and is updated to a random string like`$2a$10$5hcxpBVqwgcSfm05Oxbr2uHflURwD.AUcICYmRwPTXRlSgqoCs33q`. 

I read the document saying 
```
Patch an existing OAuth 2.0 Client. If you pass `client_secret` the secret will be updated 
and returned via the API. This is the only time you will be able to retrieve the client secret, 
so write it down and keep it safe.
```
But still not sure if I am doing something wrong here. Did I accidentally pass the `client_secret`?

### Version

Golang SDK hydra-client-go v1.10.6

### On which operating system are you observing this issue?

macOS

**Comment by aeneasr** [comment]
Thank you for the report - that looks like a bug in Ory Hydra!

**Comment by xiaofei-du** [comment]
> Thank you for the report - that looks like a bug in Ory Hydra!

Thanks for your quick reply. May I ask if this will be fixed soon? so I can decide whether to wait or not include this in my code.

**Comment by aeneasr** [comment]
It will be fixed at some point! Contributions welcomed :)

**Comment by xiaofei-du** [comment]
Just saw that this has been fixed in https://github.com/ory/hydra/issues/2869#issue-1061139829 by nice people 👍 !
