### ISSUE TITLE
Typescript: Generate ECMAScript module

### ISSUE THREAD

**Issue by UncleSamSwiss** [ory/sdk#132]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When including the API client library in an Angular 13 project, you always get the warning:
```
Warning: [...]/auth.service.ts depends on '@ory/kratos-client'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

As this npm module is completely auto-generated, I see absolutely no issue with providing it as an ESM.

See also https://angular.io/guide/build#configuring-commonjs-dependencies:
> It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application.

### Describe your ideal solution

The npm package https://www.npmjs.com/package/@ory/kratos-client is also an ESM.

### Workarounds or alternatives

Add the file to the CommonJS ignore list; but this might cause the bundle to become larger than needed.

### Version

"@ory/kratos-client": "^0.8.2-alpha.1"

**Comment by aeneasr** [comment]
Phew, I am completely out of my league here. Last time I had to work with modules I was crying 😆 . One problem we have is that we can't really change things in the generated code unless we change something upstream in OpenAPI Generator. I'm not sure if there is a good workaround for this.

Maybe @MicLeey has some ideas here.

**Comment by UncleSamSwiss** [comment]
Honestly I'm no ESM expert either, but my best guess would be that one or two lines of configuration in the package.json could already be enough.

Perhaps have a look at this (but no clue if it helps): https://github.com/gfmio/typescript-esm-cjs-hybrid-example

**Comment by MicLeey** [comment]
Looks like the generated SDK actually does export a module:

```js
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./api"), exports);
__exportStar(require("./configuration"), exports);
```

It doesn't set an export in the package.json file when it is generated though:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/package.mustache

I am guessing Angular triggers this warning by parsing the `exports` or `type` field in `package.json`.

@aeneasr I think setting the `supportsES6` flag to `true` on the generator might fix this, but I don't know if this is a breaking change for some.

**Comment by aeneasr** [comment]
Ah, that is entirely possible to be the case, and that could potentially fix it. I think we can just try it and if it breaks we'll fix it in the next version.

**Comment by aeneasr** [comment]
https://github.com/ory/sdk/blob/master/config/client/typescript.yml#L4 is already `true`

**Comment by MicLeey** [comment]
Looks like this is underway for `typescript-fetch` https://github.com/OpenAPITools/openapi-generator/pull/11720 
If accepted & merged, I will submit a similar PR for `typescripot-axios`

Until then we could patch this through a script that is run after sdk generation, but let's see what happens to the above PR

**Comment by JacobMillward** [comment]
Just bumping this issue; https://github.com/OpenAPITools/openapi-generator/pull/11720 is long since merged.

**Comment by jonas-jonas** [comment]
There seem to be a few type changes, that would break existing users of the SDK. We might get away with releasing a new minor version here, but in the end the result will be compile-time issues in users of the package. Which, IMO, means we can only do the update in a major version update. 

WDYT @aeneasr?

**Comment by dmitrigrabov** [comment]
Would you be able to publish OpenAPI specs from https://github.com/ory/sdk/tree/master/spec to `npm`? That would allow folks to generate own clients using preferred libraries and config
