### ISSUE TITLE
Go: generated hydra-client-go v1.11.4 is wrong? 

### ISSUE THREAD

**Issue by Codebreaker101** [ory/sdk#152]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Just started to checkout hydra and it seems that the API generated for v1.11.4 is for Oathkeeper API and not for Hydra. Compared to v1.10.6 the API is different and all the file headers say that is is for Oathkeeper API

### Reproducing the bug

https://github.com/ory/hydra-client-go/tree/v1.11.4

https://github.com/ory/hydra-client-go/tree/v1.10.6

### Version

v1.11.4

**Comment by aeneasr** [comment]
Hello, with Hydra 1.11 we switched the OpenAPI Generator from version 2 to version 3 to match all the other projects. If you want to generate 1.10.x-style APIs you can use this:

```
swagger generate client -f ./spec/swagger.json -t target_directory -A Ory_Hydra
```

in the project's root

**Comment by Codebreaker101** [comment]
Thanks for the response. I was confused by the header of each file that states its an Oathkeeper API:

```
/*
 * Ory Oathkeeper API
 *
 * Documentation for all of Ory Oathkeeper's APIs. 
 *
 * API version: v1.11.4
 * Contact: hi@ory.sh
 */
```
[Example](https://github.com/ory/hydra-client-go/blob/master/model_accept_consent_request.go)

**Comment by aeneasr** [comment]
Oh, yeah, that is indeed confusing! The code base is correct though for the right project :)

**Comment by aeneasr** [comment]
I think this has been resolved on master already and we just need to push another release to fix the header!

**Comment by Codebreaker101** [comment]
Great!
