### ISSUE TITLE
JSON deserialization issue of selfservice API in Java SDK

### ISSUE THREAD

**Issue by s-te-fa-n** [ory/sdk#154]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

We have just started evaluating Ory Kratos and Ory Cloud as a cloud service for us.
I´m currently working with Ory Kratos Java SDK, to get connected via API to Ory Cloud v0.8.3-alpha.1.pre.0.0.20220221123934-668f6b246db1 and got into a JSON deserialization error. I´m trying to `initializeSelfServiceLoginFlowWithoutBrowser()` of V0alpha2API, where I get a `java.lang.IllegalArgumentException: field sh.ory.kratos.model.UiNode.attributes has type sh.ory.kratos.model.UiNodeAttributes, got sh.ory.kratos.model.UiNodeInputAttributes`. It looks pretty close to #75 .
#75 was solved with Ory Kratos v0.7. I have checked several versions of Ory Kratos v0.7 Java SDK, which worked as expected, but with v0.8.0-alpha2 and newer I see the IllegalArgumentException again.

### Reproducing the bug

Kratos Java SDK

1. init API client: `ApiClient apiClient = Configuration.getDefaultApiClient();`
2. set path, e.g.: `apiClient.setBasePath("https://playground.projects.oryapis.com/api/kratos/public");`
3. init V0alpha2API: `V0alpha2Api oryApiAlpha2 = new V0alpha2Api(apiClient);`
4. init self service login flow: `oryApiAlpha2.initializeSelfServiceLoginFlowWithoutBrowser(null, null, null);`

### Relevant log output

```shell
W/System.err: java.lang.IllegalArgumentException: field sh.ory.kratos.model.UiNode.attributes has type sh.ory.kratos.model.UiNodeAttributes, got sh.ory.kratos.model.UiNodeInputAttributes
W/System.err:     at java.lang.reflect.Field.set(Native Method)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:133)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
W/System.err:     at sh.ory.kratos.JSON.deserialize(JSON.java:232)
W/System.err:     at sh.ory.kratos.ApiClient.deserialize(ApiClient.java:795)
W/System.err:     at sh.ory.kratos.ApiClient.handleResponse(ApiClient.java:1001)
W/System.err:     at sh.ory.kratos.ApiClient.execute(ApiClient.java:925)
W/System.err:     at sh.ory.kratos.api.V0alpha2Api.initializeSelfServiceLoginFlowWithoutBrowserWithHttpInfo(V0alpha2Api.java:2349)
W/System.err:     at sh.ory.kratos.api.V0alpha2Api.initializeSelfServiceLoginFlowWithoutBrowser(V0alpha2Api.java:2326)
```

### Version

v0.8.0-alpha2 and newer

### On which operating system are you observing this issue?

Linux

**Comment by s-te-fa-n** [comment]
It seems to be related with the "discriminator" updates in ".schema/openapi/patches/schema.yaml" of commit [59e808e8dc6339da59bbe08ebbcf7b840e3fdd50 ](https://github.com/ory/kratos/commit/59e808e8dc6339da59bbe08ebbcf7b840e3fdd50) (Ory Kratos repo).
If I remove the following:
```
.registerTypeSelector(UiNodeAttributes.class, new TypeSelector<UiNodeAttributes>() {
                    @Override
                    public Class<? extends UiNodeAttributes> getClassForElement(JsonElement readElement) {
                        Map<String, Class> classByDiscriminatorValue = new HashMap<String, Class>();
                        classByDiscriminatorValue.put("anchor", UiNodeAnchorAttributes.class);
                        classByDiscriminatorValue.put("image", UiNodeImageAttributes.class);
                        classByDiscriminatorValue.put("input", UiNodeInputAttributes.class);
                        classByDiscriminatorValue.put("script", UiNodeScriptAttributes.class);
                        classByDiscriminatorValue.put("text", UiNodeTextAttributes.class);
                        classByDiscriminatorValue.put("uiNodeAnchorAttributes", UiNodeAnchorAttributes.class);
                        classByDiscriminatorValue.put("uiNodeImageAttributes", UiNodeImageAttributes.class);
                        classByDiscriminatorValue.put("uiNodeInputAttributes", UiNodeInputAttributes.class);
                        classByDiscriminatorValue.put("uiNodeScriptAttributes", UiNodeScriptAttributes.class);
                        classByDiscriminatorValue.put("uiNodeTextAttributes", UiNodeTextAttributes.class);
                        classByDiscriminatorValue.put("uiNodeAttributes", UiNodeAttributes.class);
                        return getClassByDiscriminator(classByDiscriminatorValue,
                                getDiscriminatorValue(readElement, "node_type"));
                    }
          })
```
generated java code in "kratos-client-java/src/main/java/sh/ory/kratos/JSON.java" below:
```
public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
```
and compile Java SDK with Maven `mvn clean package`, it is working.

With this workaround it seems  that it is working for my current SDK evaluation purpose, but wouldn´t be useful for a release.

**Comment by s-te-fa-n** [comment]
I changed library to jersey2. With this library it is working without the discriminator problem

**Comment by Empyreans** [comment]
Could you please elaborate how exactly you fixed the problem? You switched the Json library?

**Comment by s-te-fa-n** [comment]
The underlying openapi-generator supports several http libraries (see "library" at [openapi-generator.tech](https://openapi-generator.tech/docs/generators/java#config-options)). Default is "okhttp-gson" which causes the discriminator problems in my case.
In "sdk" section of Ory Kratos Makefile (Ory Kratos root directory), there is a call of "openapi-generator-cli". I added the jersey2 library.
It looks now as following (I added the "--additional-properties..." line):
```
npm run openapi-generator-cli -- generate -i "spec/api.json" \
    -g java \
    -o "internal/httpclient" \
    --additional-properties=library=jersey2 \
```
I hope this helps to unserstand what I did.

Jersey2 was working in my case. I´m not sure if it makes sense as a general solution

**Comment by aeneasr** [comment]
Thank you for the reply! Switching generators is a possibility. Unfortunately I have very little experience with Java and don’t really know what libraries are en vogue and which ones aren’t. It also depends a bit on the support of the generator in the openapi tooling. @piotrmsc do you have experience with these libs in Java?

**Comment by notmeta** [comment]
Getting this too, noticed it only happens with `null`/`"aal1"` as aal parameters in the initialisation function, otherwise there are other errors.

**Comment by dstockhammer** [comment]
I think `jackson` would be a safer choice for the serializer. Not entirely sure why the generator uses `okhttp-gson` as default, but I'd assume it's for backwards-compatibility since changing any of the underlying libraries would be a breaking change.

For the HTTP client on the other hand I don't think there's a clear winner. `native` might be a good alternative, but that would require Java 11 which is _probably_ not acceptable. Since the default is okhttp the safest choice is probably to leave it at that 🤷 

So if you'd be willing to change the `serializationLibrary` to `jackson` I think that would be an improvement for _most_ use cases. Though it's a breaking change that **can** cause problems depending on how the library is used and what other libraries there are in the project.

**Comment by aeneasr** [comment]
Can anyone confirm that this is still an issue?

**Comment by s-te-fa-n** [comment]
No response yet and I´m currently working on other projects. I will close this issue.
