### ISSUE TITLE
Unable to deserialize ui nodes of type script

### ISSUE THREAD

**Issue by roboptics** [ory/sdk#157]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

While getting the ClientSelfServiceSettingsFlow, if webauthn is enabled, a ui node of type script is sent.

Using the SDK for .NET to deserialize this flow, an error occurs at ClientUiNodeAttributes::FromJson() because both ClientUiNodeScriptAttributes and ClientUiNodeImageAttributes can deserialize the script ui node. This happend because the script ui node has all the mandatory attributes of the ClientUiNodeImageAttributes. Adding Width and/or Height to the mandatory attributes fixes this issue.

### Reproducing the bug

1. Enable webauthn
2. Try to get / initialize the ClientSelfServiceSettingsFlow using  .NET SDK.

### Version

0.0.1-alpha.76

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Thank you for the report! Could you try a more recent version of the SDK please? :) 0.0.1-alpha.124 is the most recent

**Comment by aeneasr** [comment]
I see, I thought this might already have been fixed but apparently it has not. Thank you for the report, your analysis looks on point.

**Comment by aeneasr** [comment]
https://github.com/ory/sdk/pull/159

**Comment by aeneasr** [comment]
Ok, unfortunately my assumption was not correct. We do indeed use the dotnet generator from upstream. So I think you found a bug in the OpenAPI Generator template :/ Looking at the code, it appears that the DotNet generator is not using the discriminator value, but instead relying on typing to find the right instance:

https://github.com/ory/client-dotnet/blob/befa798bff09a5fe9f522b066c244daf29bfb7de/src/Ory.Client/Model/ClientUiNodeAttributes.cs#L216-L244

It appears that the same thing applies for the Go SDK. 

So you're right, I think the only way to work around this in the generators is to mark width/height as required. I checked the code, and it's not being "unset" anywhere, so I guess this should be a good workaround!

**Comment by aeneasr** [comment]
Ok cool, thank you! I think the changes in https://github.com/ory/kratos/pull/2322 should allow you to remove the workaround :)
