### ISSUE TITLE
Go: Add LICENSE file

### ISSUE THREAD

**Issue by drigz** [ory/sdk#161]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I'm trying to use https://github.com/google/go-licenses to generate list of licenses for the `kratos` binary. However, it prints a warning:

```
E0329 17:10:27.575194  277664 library.go:102] Failed to find license for github.com/ory/kratos-client-go: no file/directory matching regexp "^(?i)(LICEN(S|C)E|COPYING|README|NOTICE).*$" found for /home/drigz/git/ory/kratos/internal/httpclient
```

This is because there is no LICENSE file in https://github.com/ory/kratos-client-go.

### Describe your ideal solution

I'd expect kratos-client-go to contain a LICENSE file. I looked into whether I could easily send a PR, but I'm not familiar with openapi-generator, and although it has an [FAQ for adding a LICENSE file](https://openapi-generator.tech/docs/faq-extending/#how-can-i-customize-the-auto-generated-code) the linked docs are not obvious to me. Maybe you could add the following lines to `config/client/go.yml` but this is magic enough that I'm not sure it would work:

```
templateDir: .
files:
  LICENSE: {}
```

### Workarounds or alternatives

I can manually rework the output of the go-licenses tool, as I assume the SDK has the same Apache 2.0 license as the rest of the project.

### Version

kratos v0.9.0-alpha.3

**Comment by vinckr** [comment]
Hello drigz 

Thanks for reporting this.
Here is the PR that will fix it: 
https://github.com/ory/sdk/pull/162

**Comment by drigz** [comment]
Thanks for the quick fix! Glad I didn't try myself, doing it in generate.sh definitely looks much simpler :)
