### ISSUE TITLE
.NET API Client call AdminListIdentitySessionsAsync not working

### ISSUE THREAD

**Issue by roboptics** [ory/sdk#167]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Unable to call the .NET Client Api function AdminListIdentitySessionsAsync(). An error deserializing the field `authentication_methods.aal` from the ClientSession model is thrown.

This happens because the json value for this field is "", when a value belonging to `ClientAuthenticatorAssuranceLevel` is expected.

Below is a sample of the returned json response:

```
[
  ...
  {
    "id": "REDACTED",
    "active": false,
    "expires_at": "2022-01-28T20:16:12.252766Z",
    "authenticated_at": "2022-01-27T20:16:12.252766Z",
    "authenticator_assurance_level": "aal2",
    "authentication_methods": [
      {
        "method": "password",
        "aal": "",
        "completed_at": "2022-01-27T20:15:49.421883833Z"
      },
      ...
    ],
    ...
  },
  ...
]
```

### Reproducing the bug

Use the .NET Client Api to call AdminListIdentitySessionsAsync().

### Version

0.0.1-alpha.169

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Docker Compose

### Additional Context

After a detailed analysis, in our case this only seems to affect sessions that are at least a couple of weeks old. Is this a result of a recent breaking change and we do not need to worry about this in the future?

**Comment by aeneasr** [comment]
Sorry @roboptics ! I completely missed this issue. If you have problems with using the cloud system feel free to create such issues in github.com/ory/cloud as well, we have a couple of people monitoring that repo :)

Regarding your question, it looks like this is a regression? We've made a few improvements to the enums so it might be resolved, but not sure. Did this problem re-appear for you?

**Comment by roboptics** [comment]
Hello. No problem. We deleted all the older sessions to work around this issue and so far we have not noticed it again. I will close this for now. Thank you for your help.

**Comment by aeneasr** [comment]
You're welcome, sorry for the inconvenience!
