### ISSUE TITLE
Go: hydra-client-go 1.11.8 model error, json unmarshal error

### ISSUE THREAD

**Issue by sixleaveakkm** [ory/sdk#182]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I think this is the same problem resolved in version 1.11.7. 
https://github.com/ory/hydra/pull/3074
https://github.com/ory/hydra/issues/3058

hydra try to Unmarshal response with `map[string]map[string]interface{}` for some item, which I think should be `map[string]interface{}`, but got `json: cannot unmarshal ...`

This problem exists at
- `LoginRequest.OidcContext.IdTokenHintClaims`
- `ConsentRequest.OidcContext.IdTokenHintClaims`
- `OAuth2TokenIntrospection.Ext`

### Reproducing the bug

Launch hydra server, with a proper setting, and create two clients.
Use go sdk to handle login/consent requests.

For 
- `LoginRequest.OidcContext.IdTokenHintClaims`
- `ConsentRequest.OidcContext.IdTokenHintClaims`

When initial auth, pass a valid id token value as `id_token_hint`,  
this will cause that `json: cannot unmarshal ...` on endpoints:
[Get a Login Request](https://www.ory.sh/docs/hydra/reference/api#operation/getLoginRequest)
[Get Consent Request Information](https://www.ory.sh/docs/hydra/reference/api#operation/getConsentRequest)

And when `Context` is provided in `AcceptLoginRequest`, and then try to introspect the token,
`OAuth2TokenIntrospection` will give a similar error.

### Version

1.11.8

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Binary

**Comment by aeneasr** [comment]
This should be resolved now
