### ISSUE TITLE
CI is currently failing

### ISSUE THREAD

**Issue by AntiSC2** [ory/sdk#19]
CI job "publish" is currently failing:
```
failed rendering template data for definition: template execution failed for template definition: template: schematype:20:18: executing "typeSchemaType" at <(len .AllOf) gt 0>: can't give argument to non-function len .AllOf
```
This causes for example the [Kratos PyPI project](https://pypi.org/project/ory-kratos-client/) to not get updated which means that if you have installed ory-kratos-client as a dependency through there then you can't currently use the latest version of Kratos.

**Comment by aeneasr** [comment]
Thank you, this should be fixed now! The problem was an outdated go-swagger version.
