### ISSUE TITLE
Keto Client Repos Default Branch is `main`, but code is on `master`

### ISSUE THREAD

**Issue by halostatue** [ory/sdk#193]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I’m looking through the generated clients to better understand the Ory projects, and the `keto-client-*` repos appeared to be empty except for `LICENSE` files.

The default branch has been set to `main`, but the generated client code is checked into `master`.

This appears to be a configuration issue, and since this repo is the one that generates the SDKs, I figured this is the right place to report this, rather than reporting an issue on each client. The easiest fix is to change the default branch on each of the target repos; the likely correct fix (since the default branch for new repos on GitHub is `main`) is to set the target branch to be configurable.

### Reproducing the bug

Visually compare <https://github.com/ory/keto-client-js/tree/main> to <https://github.com/ory/keto-client-js/tree/master>.

### Version

n/a

**Comment by aeneasr** [comment]
Awesome analysis! I have changed the branch to master :)
