### ISSUE TITLE
GO: Error 'Index 0 out of range -1' in kratos-client-go

### ISSUE THREAD

**Issue by tjarkmeyer** [ory/sdk#198]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [x] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The following code is simply an example from the [docs](https://www.ory.sh/docs/kratos/sdk/go#using-admin-api) but it throws the error '**Index 0 out of range -1**'. The response is `nil`.

```
package main

import (
	"context"
	"fmt"
	"os"

	client "github.com/ory/kratos-client-go"
)

func main() {
	apiClient := client.NewAPIClient(&client.Configuration{
		Scheme: "https",
		Host:   "playground.projects.oryapis.com",
		DefaultHeader: map[string]string{
			"Authorization": "Bearer ory_pat_xRKLsFEOUFQFVBjd6o3FQDifaLYhabGd",
		},
	})

	adminCreateIdentityBody := *client.NewAdminCreateIdentityBody(
		"default",
		map[string]interface{}{
			"email": "foo@example.com",
			"name": map[string]string{
				"first": "foo",
				"last":  "bar",
			},
		},
	) // AdminCreateIdentityBody |  (optional)

	createdIdentity, r, err := apiClient.V0alpha2Api.AdminCreateIdentity(context.Background()).AdminCreateIdentityBody(adminCreateIdentityBody).Execute()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error when calling `V0alpha2Api.AdminCreateIdentity``: %v\n", err)
		fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
	}
	fmt.Fprintf(os.Stdout, "Created identity with ID: %v\n", createdIdentity.Id)
}
```

### Reproducing the bug

Run the code from above.

### Version

kratos-client-go v0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Ory Cloud

**Comment by vinckr** [comment]
Hello @tjarkmeyer 

check out this snippet, it should work for Ory Cloud, your example is missing the 
```
Servers: []client.ServerConfiguration{
			{
				URL: "<project-url>",
			},
```

Also please use the new [ory/client-go](https://github.com/ory/client-go), we still have to document this and migrate or rather think of a good migration process from the old SDK. I will see to update the SDK snippets in the docs accordingly.

```
package main

import (
	"context"
	"fmt"
	"github.com/ory/client-go"
)

func main() {
	conf := &client.Configuration{
		Servers: []client.ServerConfiguration{
			{
				URL: "<project-url>",
			},
		},
		DefaultHeader: map[string]string{
			"Authorization": "Bearer <pat-token>",
		},
	}

	api := client.NewAPIClient(conf)

	schemas, _, err := api.V0alpha2Api.ListIdentitySchemas(context.Background()).Execute()
	if err != nil {
		panic(err)
	}

	for _, schema := range schemas {
		fmt.Printf("SchemaID: %s\n", schema.Id)
		fmt.Printf("SchemaName: %s\n", schema.Name)
	}

	user := client.NewAdminCreateIdentityBody("<really-long-id>", map[string]interface{}{
		"email": "a-new-test2-user@example.com",
	})

	identity, _, err := api.V0alpha2Api.AdminCreateIdentity(context.Background()).AdminCreateIdentityBody(*user).Execute()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%v+\n", identity)
}
```

**Comment by tjarkm** [comment]
Works now! Thanks!
