### ISSUE TITLE
metadata_public returns null and data type verification fails

### ISSUE THREAD

**Issue by quizmoon** [ory/sdk#218]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Our users have no "metadata_public", so when we do "to_session" call we receive back "metadata_public":null
Python Client fails as it is expecting Dict in return.

Looks as "metadata_public" and "metadata_admin" have to be declared as "traits" in the:
https://github.com/ory/client-python/blob/master/ory_client/model/identity.py

Current version:
'traits': (bool, date, datetime, dict, float, int, list, str, none_type,), # noqa: E501
'metadata_admin': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},), # noqa: E501
'metadata_public': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},), # noqa: E501

Should be:
'traits': (bool, date, datetime, dict, float, int, list, str, none_type,), # noqa: E501
'metadata_admin': (bool, date, datetime, dict, float, int, list, str, none_type,), # noqa: E501
'metadata_public': (bool, date, datetime, dict, float, int, list, str, none_type,), # noqa: E501

Possible it have to be done on level of schema to apply automatically to all the future client recreation.

### Reproducing the bug

Create basic user with email / pass only and using ory-client==0.2.0a60 make request "to_session"

### Relevant log output

```shell
ory_client.exceptions.ApiTypeError: Invalid type for variable 'metadata_public'. Required value type is dict and passed type was NoneType at ['received_data']['identity']['metadata_public']
```

### Version

0.2.0a60

**Comment by aeneasr** [comment]
Thank you for the report, we'll take a look to see how to solve this!
