### ISSUE TITLE
Rust crate on crates.io outdated

### ISSUE THREAD

**Issue by hesmar** [ory/sdk#221]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The [rust crate on crates.io](https://crates.io/crates/ory-hydra-client) of the hydra client is still `v1.11.8`. It seems that there is a newer version in this repo. May the crate can be updated for easier integration in rust projects?

### Reproducing the bug

Go to [v1.11.8](https://crates.io/crates/ory-hydra-client) and see the latest version available.

### Version

latest

**Comment by aeneasr** [comment]
Looks like something went wrong during publishing! Generally we recommend using ory-client going forward :)

**Comment by fuwaneko** [comment]
@aeneasr ory-client is also 4 month [outdated](https://crates.io/crates/ory-client/versions) (0.2.0-alpha.4 while most recent should be 1.0.2).

**Comment by jonas-jonas** [comment]
Hi @fuwaneko, thanks for the report. Seems like the automatic release of the Rust SDK was still disabled. Should be fixed soon!

**Comment by fuwaneko** [comment]
@jonas-jonas looks like ory-kratos-client has been updated. Thanks, now waiting for ory-client.

**Comment by lasantosr** [comment]
> Looks like something went wrong during publishing! Generally we recommend using ory-client going forward :)
@aeneasr Can we use ory-client with self-hosted Kratos & Keto?

> @jonas-jonas looks like ory-kratos-client has been updated. Thanks, now waiting for ory-client.
I'm waiting for [ory-keto-client](https://crates.io/crates/ory-keto-client) as well

**Comment by jonas-jonas** [comment]
All Ory clients should now have their latest version available on crates.io. Please create a new issue, if you're missing a specific version. Thank you.
