### ISSUE TITLE
JavaScript SDK did not find AdminApi PublicApi

### ISSUE THREAD

**Issue by bulolo** [ory/sdk#228]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

<img width="622" alt="image" src="https://user-images.githubusercontent.com/10026498/201833603-d6eb8681-590e-468b-aac2-6ae845b2c132.png">

```
import { Configuration, PublicApi, AdminApi } from "@ory/hydra-client"

const hydraPublic = new PublicApi(
  new Configuration({
    basePath: "https://public.hydra:4444/",
  }),
)

const hydraAdmin = new AdminApi(
  new Configuration({
    basePath: "https://public.hydra:4445/",
  }),
)
```

<img width="769" alt="image" src="https://user-images.githubusercontent.com/10026498/201833638-f5277891-8bbc-41b1-beb5-bd6876bdc059.png">

can't find `PublicApi ` `AdminApi`

### Reproducing the bug

```
yarn add @ory/hydra-client
```
```
import { Configuration, PublicApi, AdminApi } from "@ory/hydra-client"

const hydraPublic = new PublicApi(
  new Configuration({
    basePath: "https://public.hydra:4444/",
  }),
)

const hydraAdmin = new AdminApi(
  new Configuration({
    basePath: "https://public.hydra:4445/",
  }),
)
```

```
src/modules/auth/auth.service.ts:6:25 - error TS2305: Module '"@ory/hydra-client"' has no exported member 'PublicApi'.

6 import { Configuration, PublicApi, AdminApi } from "@ory/hydra-client"
                          ~~~~~~~~~

src/modules/auth/auth.service.ts:6:36 - error TS2305: Module '"@ory/hydra-client"' has no exported member 'AdminApi'.

6 import { Configuration, PublicApi, AdminApi } from "@ory/hydra-client"
```

### Version

2.0.2

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
Please see https://github.com/ory/hydra/blob/master/CHANGELOG.md#breaking-changes

**Comment by bulolo** [comment]
@aeneasr

**Comment by vinckr** [comment]
> @aeneasr any diffrent between @ory/client and @ory/hydra-client@v2.0.2?

For future reference: 
When self-hosting it is recommended to use the dedicated client (hydra-client in this case).
When using Ory Network you use @ory/client

Functionally they are the same and work interchangeably, both built from ory/sdk, but Ory Network might have features that are not yet released in hydra-client.

**Comment by botosa** [comment]
If anyone stumbles into the same issue, use _OAuth2Api_ instead:
```
import { Configuration, OAuth2Api } from "@ory/hydra-client";

export const publicApi = new OAuth2Api(
  new Configuration({
    basePath: "HYDRA_PUBLIC_URL",
  })
);

export const adminApi = new OAuth2Api(
  new Configuration({
    basePath: "HYDRA_ADMIN_URL",
  })
);
```
