### ISSUE TITLE
Missing Types in Spec causing failure for Dart generated code

### ISSUE THREAD

**Issue by AllenKaplan** [ory/sdk#230]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The [following](https://github.com/ory/sdk/blob/2324e5c13c45d43c7e7b3cdc5ebc86b86b627867/spec/client/v0.2.0-alpha.64.json#L2051-L2058) two properties are missing a type causing client v0.3 (and under) openapi generated code to fail

```
          "hydra_strategies_access_token": {
            "default": "opaque",
            "description": "Defines access token type. jwt is a bad idea, see https://www.ory.sh/docs/hydra/advanced#json-web-tokens\n\nThis governs the \"strategies.access_token\" setting."
          },
          "hydra_strategies_scope": {
            "default": "wildcard",
            "description": "Defines how scopes are matched. For more details have a look at https://github.com/ory/fosite#scopes\n\nThis governs the \"strategies.scope\" setting."
          },
```

### Reproducing the bug

Attempt to import existing ory client or generate the client based on spec

### Relevant log output

![ory_client_err](https://user-images.githubusercontent.com/25397434/202925238-588daa1c-9192-404e-b15e-e67432ec3971.png)

### Version

Client <= v0.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Other

### Additional Context

I got the info as to why it was failing by reaching out to the OAS Dart maintainers on the OpenAPI slack #dart channel -- thread [here](https://openapi-generator.slack.com/archives/C045CE32RRC/p1668873102899729)

**Comment by jonas-jonas** [comment]
Hi! Thanks for the report, this does indeed seem to be a bug in our schema. It boils down to the somewhat broken generation of Enums from Go code in our swagger tool chain. The fix should be to provide a proper enum definition. We will fix this!

**Comment by aeneasr** [comment]
Fix was merged
