### ISSUE TITLE
[dotnet] KratosUiNode.GroupEnum does not contain 'code' member

### ISSUE THREAD

**Issue by lus** [ory/sdk#231]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am using the dotnet SDK to implement the UI.
No I came across the issue, that the `GetSelfServiceVerificationFlow` and `GetSelfServiceVerificationFlowAsync` methods always return `null`, even though the flow exists (I can retrieve it manually) and no exception is thrown.
I can't explain why that happens, so I hope that someone here is able to.

### Reproducing the bug

1. Set up a working `v0alpha2Api` client
2. Try to retrieve a selfservice verification flow
3. Get `null`

### Version

0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other

**Comment by lus** [comment]
It seems like I found the issue.
The account verification UI contains a node with the `group` property set to `code`.
The `KratisUiNode.GroupEnum` (https://github.com/ory/sdk/blob/master/clients/kratos/dotnet/src/Ory.Kratos.Client/Model/KratosUiNode.cs#L40) does not contain this member, so the response cannot be deserialized.

**Comment by jonas-jonas** [comment]
The Kratos SDK was updated since then, which should've solved this problem. Please re-open, if you're still experiencing issues.
