### ISSUE TITLE
Elixir SDK unlisted in documentation

### ISSUE THREAD

**Issue by mattpolzin** [ory/sdk#242]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I noticed Elixir was not listed in the SDKs supported for Keto on the following page: https://www.ory.sh/docs/keto/sdk/overview

I was going to request it but then I noticed there already _is_ an Elixir SDK in this repository. Does this mean the Elixir SDK is not supported/maintained or should it be added to the official list in the docs?

### Describe your ideal solution

Add Elixir to the list of supported SDKs in the docs. 

### Workarounds or alternatives

N/A

### Version

N/A

### Additional Context

I’m exploring adding Keto to my company’s stack and the availability of an Elixir SDK would make the experimentation much less work.

**Comment by aeneasr** [comment]
@vinckr mind taking a peak?

**Comment by vinckr** [comment]
Oh it seems we never added it to the documentation, thanks for taking a closer look! 

I assume hex.pm is the package manger of choice for Elixir and will add this to the docs after lunch: https://hex.pm/packages/ory_keto

All SDKs you can find in this repo are supported and maintained by Ory @mattpolzin

**Comment by mattpolzin** [comment]
> I assume hex.pm is the package manger of choice for Elixir

Yep.

> All SDKs you can find in this repo are supported and maintained by Ory

Thanks!

**Comment by vinckr** [comment]
Fixed https://github.com/ory/docs/commit/4b0757165f519e78c045840032c3ccd2c6dc300a, 
thanks again for letting us know Mathew!
