### ISSUE TITLE
Inaccurate pip command for installation of ory-kratos-client

### ISSUE THREAD

**Issue by yoavnash** [ory/sdk#25]
In the [README.md](https://github.com/ory/sdk/blob/master/clients/kratos/python/README.md) file of the ory-kratos-client for python it is written that the command to install this package via pip is 
```
pip install git+https://github.com/ory/sdk.git
```
However, pip complains that the file `setup.py` doesn't exist.
I ended up using this line in order to make it work:
```
pip install git+https://github.com/ory/sdk.git#subdirectory=clients/kratos/python
```

**Comment by aeneasr** [comment]
The client is now published on pypi https://pypi.org/project/ory-kratos-client/ :)
