### ISSUE TITLE
Rust ory-keto-client outdated

### ISSUE THREAD

**Issue by lasantosr** [ory/sdk#254]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The rust crate [ory-keto-client](https://crates.io/crates/ory-keto-client) is outdated and it's missing latest 0.10.0 release, build might be broken.

### Reproducing the bug

Check the latest version available on crates.io

### Version

Latest

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

Samething happened for the hydra client some time ago:
https://github.com/ory/sdk/issues/221

**Comment by zepatrik** [comment]
This should be fixed now https://crates.io/crates/ory-keto-client/0.11.0-alpha.0
