### ISSUE TITLE
Schema does not define code method for verification

### ISSUE THREAD

**Issue by DASPRiD** [ory/sdk#260]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

At the time of writing (schema version 1.1.23) the schema body for `updateVerificationFlowBody` is set to a discriminator which only supports the `link` type, pointing to the `updateVerificationFlowWithLinkMethod` component.

There is already a `updateVerificationFlowWithCodeMethodBody` defined, but it is not referenced.

This causes issues for me, as I'm using an SDK client generated from a more recent OpenAPI generator version, which actually validates the input I give it against the schema. Thus I'm unable to submit any verification requests.

### Reproducing the bug

1. Generate a JavaScript SDK with the current version of OpenAPI Generator or use https://www.npmjs.com/package/@dasprid/ory-client-fetch
2. Try to submit a verification flow with `method` set to `code`
3. See the SDK rejecting the body.

### Relevant configuration

```yml
selfservice:
  flows:
    recovery:
      enabled: true
      ui_url: http://localhost:4000/recovery
      use: code
```

### Version

1.1.23

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by jonas-jonas** [comment]
Thanks for the report, will be fixed with https://github.com/ory/kratos/pull/3213
