### ISSUE TITLE
Missing credentials_identifier in Dotnet SDK

### ISSUE THREAD

**Issue by 0xHexE** [ory/sdk#268]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

![image](https://user-images.githubusercontent.com/29942725/234881362-42a6c101-c9f5-4f7e-8e01-54098fb720e6.png)
Missing `credentials_identifier` in the parameters of the `ListIdentitiesAsync`

![image](https://user-images.githubusercontent.com/29942725/234881863-7fcfaf8c-4204-4ba8-9732-f5510ab6e101.png)

### Reproducing the bug

Install dotnet sdk `0.11.1`. 

  

### Version

0.11.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by jonas-jonas** [comment]
Hey, thanks for the report. That feature was introduced in Kratos v0.13.0, which was released, but the SDK release process failed. We are working on getting that resolved.

**Comment by 0xHexE** [comment]
Thank you for the prompt response!

**Comment by aeneasr** [comment]
I'm triggering a re-release now

**Comment by aeneasr** [comment]
By pushing this commit, you can release yourself also @jonas-jonas : https://github.com/ory/sdk/commit/03c18d8045e7db46ac790cdfdf4a5d0e54d6b5fd

Please note that kratos itself now can't be released with v0.13.1 but needs to be released with 0.13.2
