### ISSUE TITLE
Dart SDK

### ISSUE THREAD

**Issue by sachaarbonel** [ory/sdk#27]
**Is your feature request related to a problem? Please describe.**

I'd like to implement a Flutter sample application consuming the Kratos API. In order to do that I'd rather use or contribute a Dart SDK.

**Describe the solution you'd like**

Why Dart? Because of Flutter, which let you build cross-platform apps from a single codebase

**Comment by jsiedentop** [comment]
I created a pull request for this topic: https://github.com/ory/sdk/pull/50

**Comment by aeneasr** [comment]
Dart is now merged!
