### ISSUE TITLE
ErrorBrowserLocationChangeRequired: Type Error in kratos sdk for typescript ?

### ISSUE THREAD

**Issue by jossbnd** [ory/sdk#277]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am not sure but shouldn't it be type `GenericError` instead of `ErrorGeneric` ?

https://github.com/ory/sdk/blob/a7bdd86eaed50bdfc3a82d320b50f954198c367d/clients/kratos/typescript/api.ts#L304

### Reproducing the bug

in `clients/kratos/typescript/api.ts`, type of 'error' should be `GenericError`

```
/**
 * 
 * @export
 * @interface ErrorBrowserLocationChangeRequired
 */
export interface ErrorBrowserLocationChangeRequired {
    /**
     * 
     * @type {ErrorGeneric}
     * @memberof ErrorBrowserLocationChangeRequired
     */
    'error'?: ErrorGeneric;
    /**
     * Points to where to redirect the user to next.
     * @type {string}
     * @memberof ErrorBrowserLocationChangeRequired
     */
    'redirect_browser_to'?: string;
}
```

### Version

0.13.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
This should be resolved as far as I know!
