### ISSUE TITLE
Ory Client for Elixir has a typo which breaks the client

### ISSUE THREAD

**Issue by mhaagens** [ory/sdk#282]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

There is a typo in the Ory Client for Elixir on line 221 in ```lib/ory/connection.ex```:
```
 def authorization(token, _scopes) when is_binary(token) do
    {Tesla.Middlware.Headers, ["authorization", token]}
  end
```
should be
```
 def authorization(token, _scopes) when is_binary(token) do
    {Tesla.Middleware.Headers, ["authorization", token]}
  end
```

This breaks the client when using a PAT.

### Reproducing the bug

Use any token when calling ```Ory.Connection.new("TOKEN...")```

### Relevant log output

```shell
function Tesla.Middlware.Headers.call/3 is undefined (module Tesla.Middlware.Headers is not available)
```

### Version

Ory Client 1.1.41

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Ory Network

**Comment by tobbbles** [comment]
Hey @mhaagens - could you attempt to use my fork of the SDK and validate this is fixed? https://github.com/tobbbles/sdk

This was resolved upstream in https://github.com/OpenAPITools/openapi-generator/pull/14512 and is in the latest openapi-generator version; I'll open a pull request of my fork that addresses this.
