### ISSUE TITLE
UiNode decoding issue in self-service browser kratos-client-go v1.0.0

### ISSUE THREAD

**Issue by mek-yt** [ory/sdk#291]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I was using without problems the kratos server v1.0.0 with kratos-client-go v0.13.1 for the development of a self-service with golang [zelus](https://git.sr.ht/~mekyt/zelus).

But when I upgraded to the v1.0.0 of the SDK the Nodes in UiContainer are not decode anymore with only null value or empty array but with the right number of elements.

### Reproducing the bug

- Setup a development Kratos server with default
- Clone zelus `git clone https://git.sr.ht/~mekyt/zelus`
- Setup `cp .env.default .env`
- Check v0.13.1 `just run` on [http://127.0.0.1:4435](http://127.0.0.1:4435)
- Update SDK `go get -u github.com/ory/kratos-client-go` 
- Check v1.0.0 `just run`

### Version

1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

### Additional Context

I checked the data return from the API with the `http.Response` which looks ok but the the parsing failed to set the UiNode fields.

**Comment by aeneasr** [comment]
Should be fixed!
