### ISSUE TITLE
Add the ability to set custom headers

### ISSUE THREAD

**Issue by batazor** [ory/sdk#298]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

In order to link my `trace-id` to events in ory/kratos I need to add W3C headers.

Currently there is no way to add headers to requests

### Describe your ideal solution

Add method `.SetHeaders(key, value)` or `.SetHeaders(map[string]string)`

### Workarounds or alternatives

As an option is the ability to pass the query context `.Execute(ctx context.Context)` and check for the presence of `trace-span-id`

### Version

github.com/ory/client-go v1.2.11

**Comment by batazor** [comment]
As an alternative, we can add this method to the template by analogy with the `.cookie' method

```
func (r FrontendApiToSessionRequest) SetHeader(key, value string) FrontendApiToSessionRequest {
	r.SetHeader(key, value)
	return r
}
```

**Comment by aeneasr** [comment]
You can pass custom headers in the config and in the context afaik
