### ISSUE TITLE
BC breaks: fields in the SDK changed (e.g. FrontendApi > FrontendAPI; IdentityApi > IdentityAPI)

### ISSUE THREAD

**Issue by till** [ory/sdk#328]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When we update the client (go) from `v1.2.14` to `v1.6.1`, our tests are failing:

![image](https://github.com/ory/sdk/assets/27003/26b2877f-cdb7-482a-b22b-5b9b3f3ca968)

### Reproducing the bug

See above.

### Version

sdk v1.6.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
Hi, you need to replace `IdentityApi` with `IdentityAPI`!

**Comment by till** [comment]
@aeneasr Yeah, I know. But why? 😅

**Comment by aeneasr** [comment]
Because we updated the generator

**Comment by till** [comment]
Why not tag `2.x` if you're breaking integrations?

**Comment by aeneasr** [comment]
It's only the casing of some variables and not a major change to the API. This constitues a minor change in our view.
