### ISSUE TITLE
.NET packages have not been updated

### ISSUE THREAD

**Issue by red-gecko27** [ory/sdk#339]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

All .NET packages have not been updated for a few months:

- Ory.Kratos.Client: Last version 1.0.0 (https://www.nuget.org/packages/Ory.Kratos.Client/)
- Ory.Client: Last version 1.4.9 (https://www.nuget.org/packages/Ory.Client/)
...

### Reproducing the bug

see: www.nuget.org

### Version

ory/client v1.8.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Thank you - the key expired and I updated it. New versions should go out as normal
