### ISSUE TITLE
UnmarshalJSON fails for the LoginFlow type in kratos-client-go

### ISSUE THREAD

**Issue by agiix** [ory/sdk#347]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Kratos Go client (version 1.1.0) fails to correctly unmarshal the JSON response into the LoginFlow object.
This happens because it defines the [state field as a required property](https://github.com/ory/kratos-client-go/blob/789aca7a7f5b28758855e1999887a5ba67d3b354/model_login_flow.go#L650), which is not provided within the response from the Kratos instance (version 1.1.0)
An easy fix for it would be to remove the state field as a required property, [like on this fork](https://github.com/agiix/kratos-client-go/blob/5f079e21e2a06fd0260a2dcb064375acbc225e28/model_login_flow.go#L650).

### Reproducing the bug

When initiating a native login flow using something like:
```
kratosClient := client.NewAPIClient(configuration)
loginFlow, _, err := kratosClient.FrontendAPI.CreateNativeLoginFlow(context.Background()).Execute()
if err != nil {
	fmt.Println(err)
}
```
the error occurs. 

Inspecting the response using curl to initiate the flow:
```
curl -X GET \                                          
    -H 'Content-Type: application-json' \
    127.0.0.1:4433/self-service/login/api
```
 shows that there is no state field being returned at this stage of the flow:
```
{
  "id": "b63875be-64ea-48d5-84a6-ad2a04793687",
  "type": "api",
  "expires_at": "2024-03-28T22:26:36.416713342Z",
  "issued_at": "2024-03-28T22:16:36.416713342Z",
  "request_url": "http://127.0.0.1:4433/self-service/login/api",
  "ui": {
    "action": "http://kratos:4433/self-service/login?flow=b63875be-64ea-48d5-84a6-ad2a04793687",
    "method": "POST",
    "nodes": [
      {
        "type": "input",
        "group": "default",
        "attributes": {
          "name": "csrf_token",
          "type": "hidden",
          "value": "",
          "required": true,
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {}
      },
      {
        "type": "input",
        "group": "default",
        "attributes": {
          "name": "identifier",
          "type": "text",
          "value": "",
          "required": true,
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1070004,
            "text": "ID",
            "type": "info"
          }
        }
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "password",
          "type": "password",
          "required": true,
          "autocomplete": "current-password",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1070001,
            "text": "Password",
            "type": "info"
          }
        }
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "method",
          "type": "submit",
          "value": "password",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1010001,
            "text": "Sign in",
            "type": "info",
            "context": {}
          }
        }
      }
    ]
  },
  "created_at": "2024-03-28T22:16:36.446211Z",
  "updated_at": "2024-03-28T22:16:36.446211Z",
  "refresh": false,
  "requested_aal": "aal1"
}
```

### Relevant log output

```shell
2024/03/28 20:21:00 stdout: no value given for required property state
```

### Version

1.1.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Should be fixed by now
