### ISSUE TITLE
v1.11.6 adds axios to @ory/client-fetch

### ISSUE THREAD

**Issue by xqqp** [ory/sdk#353]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm using the javascript client `@ory/client-fetch`, which until `v1.9.1` worked fine. Since the version jump to `v1.11.6` axios was added to the client, as its `package.json` contains it as a dependency:

``
  "dependencies": {
    "axios": "^1.6.1"
  },
``
The fetch client was created to not use axios in the first place. I believe this is a bug. Please review.

### Reproducing the bug

Fetch  `@ory/client-fetch` with version `v1.11.6` or higher and look at the dependencies.

### Version

client version 1.11.7

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Thank you for the report, that definitely seems to be a bug in the release pipeline.

**Comment by richardpoole** [comment]
This is still broken in the latest published @ory/client-fetch package: https://www.npmjs.com/package/@ory/client-fetch/v/1.11.7
