### ISSUE TITLE
CI fails when trying to publish client

### ISSUE THREAD

**Issue by qrest** [ory/sdk#359]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The CI `publish` step fails with the following error: 

`ERROR: (gcloud.auth.activate-service-account) Unable to read file [~/.pub-cache/key-file.json]: [Errno 2] No such file or directory: '~/.pub-cache/key-file.json'`

Please consider fixing the CI so updates are pushed to NPM again.

### Reproducing the bug

 Look at the CI error logs

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
I fixed the pipeline, and now all languages get built again
