### ISSUE TITLE
Typescript SDK does not accept return_to parameter in self-service flows.

### ISSUE THREAD

**Issue by marcinkoziej** [ory/sdk#36]
As far as I understand, the self-service flow initiation methods should allow to pass `return_to` parameter to Kratos. However, these methods do not accept any query parameters.

**Comment by aeneasr** [comment]
Yup, we should fix that! But also keep in mind that these endpoints should not be consumed by regular browser requests only.

**Comment by marcinkoziej** [comment]
I was trying to get the kratos reference self-service app to do return_to after successful sign in (I am using oathkeeper to redirect non-authenticated user to the self service app). I believe this change in kratos-client lib is needed for the self service app to support this functionality!

**Comment by aeneasr** [comment]
No, just add `return_to` here: https://github.com/ory/kratos-selfservice-ui-node/blob/master/src/routes/auth.ts#L58

**Comment by marcinkoziej** [comment]
:thinking: I'm on `v0.4.6.-alpha1` – did the api change in master ?

In `v0.4.6` it's:           `${config.kratos.browser}/self-service/browser/flows/${type}`
In master it's:           `${config.kratos.browser}/self-service/${type}/browser`

I also need to use the Kratos master for this right?

**Comment by marcinkoziej** [comment]
Ok I see [Kratos issue 635](https://github.com/ory/kratos/issues/635).

Just want to confirm - I should run Kratos and node self service from master?
