### ISSUE TITLE
Ory client side libraries should be Tree Shakeable 

### ISSUE THREAD

**Issue by md-owes** [ory/sdk#362]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

All modern library libraries support tree shaking feature in order to reduce bundle size. In case of @ory/client, it is not, (at least not fully) as it produces a runtime bundle of 2.3mb which contributes to longer loading times of my application.

### Describe your ideal solution

Instead of one big file api.ts consisting of ~27k lines of code, it should be broken down into several smaller class files that embraces SOLID design principles. Few more optimizations that can be applied to a library to make it tree shakeable is explained in the below articles

https://cube.dev/blog/how-to-build-tree-shakeable-javascript-libraries
https://blog.theodo.com/2021/04/library-tree-shaking/

### Workarounds or alternatives

no workarounds as we are forced to download entire @ory/client library even if we are consuming few classes, components or functions

### Version

1.12.1

**Comment by aeneasr** [comment]
You can use `@ory/client-fetch` for this now!

**Comment by aeneasr** [comment]
https://www.npmjs.com/package/@ory/client-fetch

**Comment by md-owes** [comment]
will give it a try this week. thanks.
