### ISSUE TITLE
Publish Java kratos-client 1.2 to maven central

### ISSUE THREAD

**Issue by kamilkloch** [ory/sdk#363]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Ory kratos 1.2 has been released, the latest release on maven central is still 1.1: https://mvnrepository.com/artifact/sh.ory.kratos/kratos-client

### Describe your ideal solution

Publish Java kratos-client 1.2 to maven central

### Workarounds or alternatives

Publish Java kratos-client 1.2 to maven central

### Version

1.1

**Comment by aeneasr** [comment]
The pipeline is fixed now, so the upcoming release will appropriately trigger a build!
