### ISSUE TITLE
TypeError: import_util.TextEncoder is not a constructor if use @ory/client for SSR project

### ISSUE THREAD

**Issue by tamtakoe** [ory/sdk#375]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

@ory/client doesn't work for SSR rendering

### Reproducing the bug

I'm using @ory/client for Angular 18 project
```ts
import { Configuration, OAuth2Api, IdentityApi, FrontendApi, LoginFlow, RegistrationFlow, LogoutFlow, RecoveryFlow, SettingsFlow, VerificationFlow, GenericError, UiContainer, UiNodeAttributes, UiNodeInputAttributes, UiNodeTextAttributes, UiNodeImageAttributes } from "@ory/client"
...
```
And see the runtime error

### Relevant log output

```shell
2:43:58 PM [vite] Error when evaluating SSR module /@fs/Users/myname/dev/myproject/.angular/cache/18.2.2/vite/deps_ssr/@ory_client.js?v=58d55296:
|- TypeError: import_util.TextEncoder is not a constructor
    at eval (/Users/myname/dev/myproject/.angular/cache/18.2.2/vite/deps_ssr/@ory_client.js:12400:19)
    at async instantiateModule (file:///Users/myname/dev/myproject/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52844:5)
```

### Version

1.14.5

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by AlienDarkCat** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by aeneasr** [comment]
Can you please try `@ory/client-fetch` which no longer needs axios? Thanks!
