### ISSUE TITLE
Typescript Hydra SDK: camel-cased types mismatch API snake-case values

### ISSUE THREAD

**Issue by fraxachun** [ory/sdk#40]
As far as I see the SDK returns the snake-cased result from the API whilst being typed camel-cased. I suppose there is some kind of a converting step missing.

**Comment by aeneasr** [comment]
Could you please be a bit more specific? At least a code example and the version you're using, thanks.

**Comment by fraxachun** [comment]
I'm using @oryd/hydra-client in Version 1.8.5.
If I request an oAuth2Client like this:
```
    const hydraService = new AdminApi({ basePath: "http://localhost:4445" });
    const client = await hydraService.getOAuth2Client("my-oauth2-client"));
    console.log(client.data);
```
I get this data:
```
{
    client_id: "my-oauth2-client",
    client_name: "My OAuth2 Client",
    ...
}

```
You can see that e.g. "client_id" is in snake-case like if you would call the REST-API directly. However, the Typescript type information for the interface OAuth2Client says it should be camel-cased: https://github.com/ory/sdk/blob/master/clients/hydra/typescript/api.ts#L576

**Comment by aeneasr** [comment]
Ah, yes! Thank you, I also noticed that in the Kratos SDK and have since resolved it (see https://github.com/ory/sdk/commit/3774cb93052e8d14a90aeb5a038fad78065947f9). So the next release should have this return correctly!
