### ISSUE TITLE
kratos: route mismatch for specs v0.5.3-alpha.1

### ISSUE THREAD

**Issue by davidcheung** [ory/sdk#43]
https://github.com/ory/sdk/blob/master/spec/kratos/v0.5.3-alpha.1.pre.0.json#L1132 

I believe this should be `/self-service/settings/browser` instead of `/self-service/settings/browser/flow`  since `0.5.0+`
this leads to a 404 when using the sdk to fetch the settings form

I'm not sure what the workflow for generating the SDKs so didn't make a PR

**Comment by tacurran** [comment]
@davidcheung  please take a look at the SDK creation setup here https://github.com/ory/kratos/blob/master/.circleci/config.yml

Perhaps you can explain the error in a PR ? I can also help you with the problem resolution then

**Comment by davidcheung** [comment]
@tacurran the error is the specs have the wrong url, it shouldn't have `/flow` at the end since 0.5.0 
1. The docs have it without `/flow` trailing  https://www.ory.sh/kratos/docs/self-service/flows/user-settings#profile-updates-for-browser-clients
2. settings's api flow has it without `/flow` trailing https://github.com/ory/sdk/blob/master/spec/kratos/v0.5.3-alpha.1.pre.0.json#L1093
3. registration has it without `/flow` trailing https://github.com/ory/sdk/blob/master/spec/kratos/v0.5.3-alpha.1.pre.0.json#L950
4. login has it without `/flow` trailing https://github.com/ory/sdk/blob/master/spec/kratos/v0.5.3-alpha.1.pre.0.json#L601

**Comment by davidcheung** [comment]
Please note that the code on kratos side is fine, its just the SDK has the wrong specs on the path so if you use `initializeSelfServiceSettingsViaBrowserFlow` you will get a 404
