### ISSUE TITLE
Admin API createOAuth2Client not working correctly

### ISSUE THREAD

**Issue by ab316** [ory/sdk#44]
It seems that in the latest Typescript version (v1.9.0-alpha.2) and v1.8.5 the Admin API's createOAuth2Client method is not creating the client correctly with the provided parameters. It's like the OAuth2Client body object is not being used. 

I feel that this line in sdk/api.ts could be the problem:
`localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");`

since the body has field names like "clientId" but the REST API expects names like "client_id".

Previously it was using a customer serializer in v1.7.0;
`
body: models_1.ObjectSerializer.serialize(body, "OAuth2Client")
`

To Reproduce
1. Call the createOauth2Client method of AdminApi

**Comment by aeneasr** [comment]
Could you show how you are calling the method please?

**Comment by ab316** [comment]
Hi,
Thank you for the quick response,
It seems to have been fixed in version 1.9.0-alpha.2 where the OAuth2Client fields have been renamed with under_scores instead of camelCase.
