### ISSUE TITLE
Rust SDK

### ISSUE THREAD

**Issue by mojotalantikite** [ory/sdk#47]
I wanted to see if there was any interest in a Rust SDK for ORY services. I'd be happy to help get it together and test it out.

One issue I hit trying to test Rust openapi generation locally just now is that the openjdk:12-alpine Docker image doesn't support ARM and I'm currently using the new M1 Apple silicon. Do you have plans to move to a base Docker image that does support ARM? I'd be up for helping with that in a separate issue if so, otherwise I can switch to an old Intel mac to help with this one. Thanks!

**Comment by zepatrik** [comment]
Supporting ARM will be on our list at some point, so if you want to contribute that would be awesome.
Regarding Rust, let's wait for some feedback from the community there.

**Comment by aeneasr** [comment]
ARM is now merged :)

**Comment by aeneasr** [comment]
Rust is now merged!
