### ISSUE TITLE
Python client username/password are not sent

### ISSUE THREAD

**Issue by ericdevries** [ory/sdk#55]
Tried to use basic authentication with the python client, but it simply does not work. This is the code:

```python
config = ory_hydra_client.Configuration(
    host=app.config["ORY_HOST"],
    username="username",
    password="password",
)  

client = ory_hydra_client.ApiClient(config)

api_instance = admin_api.AdminApi(client)

# error!
api_instance.get_login_request(challenge)
```

What am I doing wrong?

**Comment by aeneasr** [comment]
Please provide more info, what error, what did you expect to happen, what are you trying to do, logs, ... etc.
