### ISSUE TITLE
[Hydra, Java Client] Please DO NOT use weird third-party date lib

### ISSUE THREAD

**Issue by UkonnRa** [ory/sdk#58]
@aeneasr In [Hydra Java Client](https://github.com/ory/sdk/blob/b8fc063b15e81ae73f824fa23345a372008142ed/clients/hydra/java/src/main/java/sh/ory/hydra/model/OAuth2Client.java#L28) you just used a weird third-party date lib, please do not use it but Java8 Time instead.

**Problem**

In [the OpenAPI doc](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/java.md) you can see the default value of `dateLibrary` is `threetenbp`. Please set it explicitly to `java8`

Maybe other projects contain the same issue

**Comment by aeneasr** [comment]
Nice find, would you be up for a PR to fix this? The config templates are here: https://github.com/ory/sdk/tree/master/config/client
