### ISSUE TITLE
What happened to the crate for rust?

### ISSUE THREAD

**Issue by Zageron** [ory/sdk#67]
It's not up on crates anymore. :(

**Comment by aeneasr** [comment]
Which one?

**Comment by Zageron** [comment]
Both hydra and Kratos are missing.  Keto is out of date. I also don't think they are published by Ory anymore, even though there are links.

**Comment by aeneasr** [comment]
Looks like they were actually never published in the first place as the task for rust is missing in: https://github.com/ory/sdk/blame/master/scripts/release.sh

**Comment by Zageron** [comment]
Thank you. Any idea when they might show up? :)

**Comment by aeneasr** [comment]
Hopefully with the next releases
