### ISSUE TITLE
Can't install kratos-client-go

### ISSUE THREAD

**Issue by dankobgd** [ory/sdk#73]
**server info**
server_version: ory_kratos v0.6.0.alpha2

**client_sdk**
language: go
version: v0.6.1-alpha.1

**bug info**

I am using go version go1.16.3 linux/amd64
I can't install the client package at all with: go get github.com/ory/kratos-client-go
I uninstalled everything go related on my machine, and clean installed again and deleted every package and everything, and every other third party package works for me normally with go modules except kratos-client-go.
I get the same error that functions/types are redeclared in this block

you have the same declarations in api_admin.go and api_public.go

for example 
```go
type ApiGetSchemaRequest struct {
	ctx context.Context
	ApiService *PublicApiService
	id string
}
```
is declared in both of them so it's obviously invalid, you need to have different package name then. Not sure what i am missing but this is how it is and it can't work like that.

**error log:**
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:31:6: ApiGetSchemaRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:564:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:38:30: ApiGetSchemaRequest.Execute redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:571:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:156:6: ApiGetSelfServiceErrorRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:689:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:162:40: ApiGetSelfServiceErrorRequest.Error_ redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:695:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:167:40: ApiGetSelfServiceErrorRequest.Execute redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:700:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:302:6: ApiGetSelfServiceLoginFlowRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:835:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:454:6: ApiGetSelfServiceRecoveryFlowRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:987:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:596:6: ApiGetSelfServiceRegistrationFlowRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:1129:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:748:6: ApiGetSelfServiceSettingsFlowRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:1281:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:918:6: ApiGetSelfServiceVerificationFlowRequest redeclared in this block
        previous declaration at ../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_admin.go:1451:6
../../../go/pkg/mod/github.com/ory/kratos-client-go@v0.6.1-alpha.1/api_public.go:167:40: too many errors

**Comment by aeneasr** [comment]
Thank you, I can reproduce this!
