### ISSUE TITLE
PHP SDK code generator makes Authorization headers misbehave

### ISSUE THREAD

**Issue by balazscsaba2006** [ory/sdk#8]
Hi everyone. First of all, thank you for giving the community such a great open-source tool as Hydra.

I tested out the PHP SDK and in general, it works well, except when trying to exchange the authorization code for an access token, even when setting the username and password in the configuration passed to `PublicApi`.

The generated code based on these properties
```php
   /**
     * Access token for OAuth/Bearer authentication
     *
     * @var string
     */
    protected $accessToken = '';

    /**
     * Username for HTTP basic authentication
     *
     * @var string
     */
    protected $username = '';

    /**
     * Password for HTTP basic authentication
     *
     * @var string
     */
    protected $password = '';
```
will always make this block misbehave:
```php
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
```
since the access token is never `null` (defaults to `''`), so the `Authorization` header will always have the value `Bearer `.

I can make a pull request to fix this, just point me in the rigth direction on how to regenerate the code to test the fix.

**Comment by aeneasr** [comment]
Thank you for the report! To fix this, please make a PR and/or issue report here: https://github.com/OpenAPITools/openapi-generator

It’s also possible that this was already fixed and we just need to bump the version but maybe it’s still there :)
