### ISSUE TITLE
Keto Java client not published >= v0.6.0

### ISSUE THREAD

**Issue by zepatrik** [ory/sdk#93]
**Describe the bug**

https://mvnrepository.com/artifact/sh.ory.keto/keto-client does not have the v0.6 client

**Comment by aeneasr** [comment]
I have triggered another release using the `v0.6.0-alpha.6` tag. If you plan on doing another release, please bump the patch version to `v0.6.1`. The CI build to observe is: https://github.com/ory/sdk/runs/3200936990

**Comment by aeneasr** [comment]
I don't understand, the stuff is published but with a weird tag?

https://app.circleci.com/pipelines/github/ory/sdk/410/workflows/b6ba16f3-9401-43a3-8932-a3f4b3022cb8/jobs/397

**Comment by aeneasr** [comment]
https://mvnrepository.com/artifact/sh.ory.keto/keto-client/0.6.0-alpha.6 released now
